name: Docker Image CI - Build Release.

on:
  push:
    branches: 
      - release/* 
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build the Docker image Plex
#        run: sudo ./build.sh addon-plex/plex 
#      - name: Build the Docker image Samba
#        run: sudo ./build.sh sambanas   
      - name: Publish Plex Addon
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target addon-plex/plex \
            --docker-hub salty2011      
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}       
salty2011